version: "3.8"

services:
  db:
    image: postgres:13
    container_name: serviz-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - serviz-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: serviz-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - serviz-network

volumes:
  postgres_data:

networks:
  serviz-network:
    name: serviz-network
