/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseButton: typeof import('./components/buttons/BaseButton.vue')['default']
    BaseInput: typeof import('./components/text-inputs/BaseInput.vue')['default']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    ForgottenPasswordForm: typeof import('./components/login/ForgottenPasswordForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheSnackbar: typeof import('./components/dialogs/TheSnackbar.vue')['default']
  }
}
